spring:
  #  main:
  #    log-startup-info: false

  datasource:
    url: jdbc:mysql://localhost:3306/star_db
    username: root
    password: Winsen15!!!!
  jpa:
    hibernate:
      ddl-auto: create #update
#    show-sql: true
